### ISSUE TITLE
NullPointerException when running

### ISSUE THREAD

**Issue by jakev** [jakev/GenerateAIDL#1]
java -jar ~/.dtf/binaries/GenerateAIDL-1.0.jar -i system-apps/test.apk -d
Loading DEX into object.
Creating DexDbHelper.
About to process DEX...
Writing: test.aidl
Exception in thread "main" java.lang.NullPointerException
    at com.jakev.genaidl.App.processDex(App.java:198)
    at com.jakev.genaidl.App.main(App.java:320)

**Comment by jakev** [comment]
Fixed: https://github.com/jakev/GenerateAIDL/commit/37fa0f62212caffbd39bc99856e67bd29ef2a167
